Version: "3.7"

services: 
  database_store:
    image: postgres
    container_name: database_store
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=myStore
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: myStore
    ports:
      - 3333:3333
      volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local

